services:
  - type: web
    name: api-rate-limiter-backend
    runtime: docker
    rootDir: backend-java
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: api-rate-limiter-redis
          property: connectionString
      - key: SPRING_REDIS_URL
        fromService:
          type: redis
          name: api-rate-limiter-redis
          property: connectionString
      - key: CORS_ORIGIN
        sync: false
      - key: OPEN_BROWSER_ON_STARTUP
        value: "false"

  - type: redis
    name: api-rate-limiter-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []
